### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by anapatriciarb** [LEEClab/LS_CORRIDORS#3]
Hello everyone, 

I am trying to start the simulations with the tutorial, but in the command prompt get this error: **ValueError: could not convert string to float: e=810780.34883516** 

I already converted the files from 16bits to float, and the error is still coming out. I wonder what am I doing wrong?

I don´t know if this is related or not, but when I run LS_corridors on the command prompt, it opens the GUI, but also an error appears: **ERROR: No existing MASK to remove**

Thank you so much in advance

**Comment by bniebuhr** [comment]
Hi Ana Patricia,

The message "ERROR: No existing MASK to remove" is normal and will appear every time you open LSCorridors. By default the package just remove any mask you put to your maps within GRASS and could have forgotten to remove.

Regarding the other message, I am not sure of what may be. Can you give us more details on the error message lines? You are using the trial data from the repository or using your own data?
What GRASS version are you using?

Best
Bernardo

**Comment by bniebuhr** [comment]
Dear Ana Patricia,

other users have reported the same problem as yours while running LSCorridors in GRASS GIS version 7.2. It seems that this is a problem in the GRASS module 'g.region', which is used to assess the map resolution.
I have corrected it and released the code as LSCorridors v. 1.0.1. You can download it here:
https://github.com/LEEClab/LS_CORRIDORS/releases/tag/v1.0.1

I really hope it works! Please tell me if you have any other problems.

Best wishes,
Bernardo

**Comment by anapatriciarb** [comment]
Dear Bernardo,

Thank you so much ! I will download then this version.

Best regards,

Ana Patricia

2017-09-01 10:22 GMT-05:00 Bernardo Niebuhr <notifications@github.com>:

**Comment by bniebuhr** [comment]
Hi Ana Patricia,

just to check it out, did things work with the new LSCorridors version?

**Comment by JohnWRRC** [comment]
Sera q o indioma do pc esta correto?
Em 21/09/2017 07:06, "Bernardo Niebuhr" <notifications@github.com> escreveu:

**Comment by anapatriciarb** [comment]
Hello Bernardo,

To be honest I haven't tried it yet cause I'm out of the office for two
weeks and I don't have the data for my personal computer. But I'll be back
on October and I'll let you know.

Thank you so much!

Ana Patricia



2017-09-21 15:18 GMT-05:00 John Wesley Ribeiro <notifications@github.com>:

**Comment by bniebuhr** [comment]
Hi Ana Patricia,

ok, no worries.
Other people seem to have had the same problem, and we guess this alteration in version 1.0.1 solved it.
Just let us know whether the problem continues or was solved when you have time.

Thanks.
Bernardo

**Comment by ghost** [comment]
Hi,

I have had the same problem, and it persist even with the new version you provided.

Here's the screenshot of the error message

![couldnotconvertstringtofloat](https://user-images.githubusercontent.com/23261077/33443416-82857904-d5c5-11e7-9978-dd78ee7792df.png)

Thank you for your help!

**Comment by bniebuhr** [comment]
Hi Cynthia,

It seems although you downloaded the new version, you still used the version 1.0.0 of LSCorridors.Please try the version 1.0.1, this one (it is in a different folder): https://github.com/LEEClab/LS_CORRIDORS/blob/master/_LS_Corridors_v1_0_1/LS_corridors_v1_0_1.py

Best,
Bernardo

**Comment by ghost** [comment]
Hi, Thanks for that, indeed it was not the right one. But then this UnicodeEncodeError kept me from running my simulations. Could it be a problem with my maps?
![unicodeencodeerror](https://user-images.githubusercontent.com/23261077/33490244-7fe6c350-d684-11e7-8db9-81cc705d37f4.png)

Thanks again for your time and help!

**Comment by bniebuhr** [comment]
Dear Cynthia,

Have you put some character with accents (such as é or è) in the output name, or are they present at name of one of the input files?

It seems to me that this may be the problem. I guess Python (and maybe GRASS GIS also) does not like this kind of character and returns this kind of error. You can try to avoid it by changing the output and input names of files without this characters. Can you give us a feedback on that?

More information on the same problem here:https://stackoverflow.com/questions/19833440/unicodeencodeerror-ascii-codec-cant-encode-character-u-xe9-in-position-7
(But I think the easiest way is just to avoid it, is possible)

Best,
Bernardo

**Comment by ghost** [comment]
Hi Bernardo,
Indeed that was the source of the error! Thank you.

As luck would have it, the simulations start running fine, but a bug shows up. The message is : 
"Warning : Impossible to rename the cell file"
The same error message shows up non-stop until I exit LSCorridors. 

![grasswarning](https://user-images.githubusercontent.com/23261077/33778628-7c62342e-dc17-11e7-9728-6ce2ef6f1c90.png)

By the way, I just realized my GRASS console is in french. I could translate it all for you should you need. Just ask!

Thanks again for you precious help
Cynthia

**Comment by bniebuhr** [comment]
Hi Cynthia,

It seems that, for some reason, the surface of random numbers that adds variability to the original resistance surface is not being created (it is called 'aleat' within the script). But I cannot figure it out why.
Can you send me your log file?
It is a text file that's created in each simulation, it starts with "___Log_Year_....txt"

You can send me directly if you prefer: bernardo_brandaum@yahoo.com.br

Best
Bernardo
